### 0-1. OAuth2 Google 로그인
# 브라우저에서 아래 URL 접속 후 Google 계정으로 로그인
# 로그인 후 백엔드에서 리다이렉트되고 토큰이 쿠키에 저장됨
GET http://localhost:8080/oauth2/authorization/google

### 0-2. OAuth2 Kakao 로그인
# 브라우저에서 아래 URL 접속 후 Kakao 계정으로 로그인
# 로그인 후 백엔드에서 리다이렉트되고 토큰이 쿠키에 저장됨
GET http://localhost:8080/oauth2/authorization/kakao

### 1. 토큰 재발급 테스트
POST http://localhost:8080/api/auth/refresh
Cookie: refreshToken={{REFRESH_TOKEN}}
### 2. 로그아웃 테스트
POST http://localhost:8080/api/auth/logout
Authorization: Bearer {{JWT_TOKEN}}

// eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlVTRVIiLCJuYW1lIjoi7LWc7ISx7JqwIiwiZW1haWwiOiJncmVlbnRqZGRuQGdtYWlsLmNvbSIsInByb2ZpbGVJbWFnZVVybCI6IiIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzg5MjM2MDQsImV4cCI6MTc3ODk2NjgwNH0.GKHPR5yzBZxt87YBtaiVI40E01oe4S0jBLXqHUU5njg

### 3-1. 회원 정보 수정 테스트 (닉네임만)
PUT http://localhost:8080/api/auth/update
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "nickname": "최성후이잉"
}
--WebAppBoundary--

### 3-2. 회원 정보 수정 테스트 (닉네임 + 프로필 이미지)
PUT http://localhost:8080/api/auth/update
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "nickname": "최성잉"
}
--WebAppBoundary
Content-Disposition: form-data; name="profileImage"; filename="test-image2.png"
Content-Type: image/png

< ./test-image.png
--WebAppBoundary--
### 4. 회원 탈퇴 테스트
DELETE http://localhost:8080/api/auth/delete
Authorization: Bearer {{JWT_TOKEN}}
Cookie: refreshToken={{REFRESH_TOKEN}}